In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN
from keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [ ]:
#hidden_size=3
model=Sequential()
model.add(SimpleRNN(3, input_shape=(2,10)))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#batch size 설정
model=Sequential()
model.add(SimpleRNN(3, batch_size=8,input_shape=(2,10)))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#return_sequences=True
model=Sequential()
model.add(SimpleRNN(3, batch_size=8,input_shape=(2,10),return_sequences=True))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_7 (SimpleRNN)     (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#Deep RNN
model = Sequential()
model.add(SimpleRNN(3,batch_size=8,input_shape=(2,10),return_sequences = True))
model.add(SimpleRNN(3,batch_size=8,input_shape=(2,10),return_sequences = True))
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_16 (SimpleRNN)    (8, 2, 3)                 42        
_________________________________________________________________
simple_rnn_17 (SimpleRNN)    (8, 2, 3)                 21        
Total params: 63
Trainable params: 63
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#Bidirectional RNN
model = Sequential()
model.add(Bidirectional(SimpleRNN(3, return_sequences = True), 
                        input_shape=(2, 10)))
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_1 (Bidirection (None, 2, 6)              84        
Total params: 84
Trainable params: 84
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional,GRU

In [ ]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [ ]:
#모든 시점의 은닉상태(최종 timestep인 4로 1,4,3 shape이 맞춰짐)
#마지막 시점의 은닉상태
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[ 0.99202687 -0.8905591   0.7390852 ]
  [ 0.9817916  -0.7266794   0.5457633 ]
  [ 0.69707584 -0.86732656 -0.41346505]
  [ 0.9979529   0.04790891  0.8568031 ]]], shape: (1, 4, 3)
last hidden state : [[0.9979529  0.04790891 0.8568031 ]], shape: (1, 3)


In [ ]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[-0.1577847   0.05021674 -0.12941185]], shape: (1, 3)
last hidden state : [[-0.1577847   0.05021674 -0.12941185]], shape: (1, 3)
last cell state : [[-0.3898736   0.08988121 -0.32986447]], shape: (1, 3)


In [ ]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, 
                            kernel_initializer=k_init, 
                            bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.63031393 0.63031393 0.63031393]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [ ]:
gru = GRU(3, return_sequences=True, return_state=True)
whole_sequence_output, final_state  = gru(train_X)

print('whole_sequence_output : {}, shape: {}'.format(whole_sequence_output, whole_sequence_output.shape))
print('final state : {}, shape: {}'.format(final_state , final_state .shape))

whole_sequence_output : [[[-0.05192707 -0.51655644  0.67229193]
  [-0.03286002  0.22752218  0.79793173]
  [-0.14392087  0.76349324  0.24715751]
  [-0.13851903  0.6697672   0.43647963]]], shape: (1, 4, 3)
final state : [[-0.13851903  0.6697672   0.43647963]], shape: (1, 3)


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN
import numpy as np
from tensorflow.keras.utils import to_categorical

In [ ]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
sequences = list()
for line in text.split('\n'): # Wn을 기준으로 문장 토큰화
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
max_len=max(len(l) for l in sequences) # 패딩을 위해 가장 긴 샘플의 길이
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1] #마지막 단어 레이블화
y = to_categorical(y, num_classes=vocab_size)

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1)) # 레이블을 분리하였으므로 이제 X의 길이는 5
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

In [ ]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 데이터에 대한 패딩
        resulttwo = model.predict(encoded, verbose=0) #predict_classes 없어져서 코드 바꿈
        result=np.argmax(resulttwo,axis=1)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [ ]:
print(sentence_generation(model, t, '경마장에', 4))

경마장에 있는 말이 뛰고 있다


In [ ]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from nltk.corpus.reader import PlaintextCorpusReader
from nltk.corpus import brown
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM
import nltk

In [ ]:
nltk.download('brown')

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.


True

In [ ]:
def repreprocessing(s):
    s=s.encode("utf8").decode("ascii",'ignore')
    return ''.join(c for c in s if c not in punctuation).lower() 
text=[repreprocessing(z) for z in [(' '.join(x)).replace('  ',' ') for x in brown.sents()[:300]]]
text[:5]

['the fulton county grand jury said friday an investigation of atlantas recent primary election produced  no evidence  that any irregularities took place ',
 'the jury further said in termend presentments that the city executive committee  which had overall charge of the election   deserves the praise and thanks of the city of atlanta  for the manner in which the election was conducted ',
 'the septemberoctober term jury had been charged by fulton superior court judge durwood pye to investigate reports of possible  irregularities  in the hardfought primary which was won by mayornominate ivan allen jr ',
 ' only a relative handful of such reports was received   the jury said   considering the widespread interest in the election  the number of voters and the size of this city  ',
 'the jury said it did find that many of georgias registration and election laws  are outmoded or inadequate and often ambiguous  ']

In [ ]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 1787


In [ ]:
sequences = list()

for line in text: # 1,214 개의 샘플에 대해서 샘플을 1개씩 가져온다.
    encoded = t.texts_to_sequences([line])[0] # 각 샘플에 대한 정수 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
sequences[:11]

[[1, 49],
 [1, 49, 25],
 [1, 49, 25, 108],
 [1, 49, 25, 108, 23],
 [1, 49, 25, 108, 23, 8],
 [1, 49, 25, 108, 23, 8, 215],
 [1, 49, 25, 108, 23, 8, 215, 30],
 [1, 49, 25, 108, 23, 8, 215, 30, 292],
 [1, 49, 25, 108, 23, 8, 215, 30, 292, 2],
 [1, 49, 25, 108, 23, 8, 215, 30, 292, 2, 410],
 [1, 49, 25, 108, 23, 8, 215, 30, 292, 2, 410, 717]]

In [ ]:
index_to_word={}
for key, value in t.word_index.items(): # 인덱스를 단어로 바꾸기 위해 index_to_word를 생성
    index_to_word[value] = key

print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))

빈도수 상위 582번 단어 : sherman


In [ ]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]
y = to_categorical(y, num_classes=vocab_size)

샘플의 최대 길이 : 52


In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
# y데이터를 분리하였으므로 이제 X데이터의 길이는 기존 데이터의 길이 - 1
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

In [ ]:
print(sentence_generation(model, t, 'how', 6))

how generally argued of the fair homes


In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
# y데이터를 분리하였으므로 이제 X데이터의 길이는 기존 데이터의 길이 - 1
model.add(GRU(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=50, verbose=2)

Epoch 1/50


KeyboardInterrupt: ignored

In [ ]:
text='''Numb and broken, here I stand alone,
Wondering what were the last words I said to you.
Hoping, praying that I'll find a way to turn back time.
Can I turn back time?

What would I give to behold the smile, the face of love.
You never left me. The rising sun will always speak your name.

Numb and broken, here I stand alone,
Wondering what were the last words I said to you.
It won't be long. We'll meet again.

What would I give to behold the smile, the face of love.
You never left me. The rising sun will always speak your name.

It won't be long, we'll meet again.
Your memory is never passing.
It won't be long, we'll meet again.
My love for you is everlasting.

I mourn for those who never knew you.
I mourn for those who never knew you.

It won't be long, we'll meet again.
Your memory is never passing.
It won't be long, we'll meet again.
My love for you is everlasting.'''
tokens = text.split() # '\n 제거'
text = ' '.join(tokens)
char_vocab = sorted(list(set(text))) # 중복을 제거한 글자 집합 생성
vocab_size=len(char_vocab)
char_to_index = dict((c, i) for i, c in enumerate(char_vocab)) # 글자에 고유한 정수 인덱스 부여
print(char_to_index)
length = 11
sequences = []
for i in range(length, len(text)):
    seq = text[i-length:i] # 길이 11의 문자열을 지속적으로 만든다.
    sequences.append(seq)
X = []
for line in sequences: # 전체 데이터에서 문장 샘플을 1개씩 꺼낸다.
    temp_X = [char_to_index[char] for char in line] # 문장 샘플에서 각 글자에 대해서 정수 인코딩을 수행.
    X.append(temp_X)
sequences = np.array(X)
X = sequences[:,:-1]
y = sequences[:,-1]
sequences = [to_categorical(x, num_classes=vocab_size) for x in X] # X에 대한 원-핫 인코딩
X = np.array(sequences)
y = to_categorical(y, num_classes=vocab_size)

{' ': 0, "'": 1, ',': 2, '.': 3, '?': 4, 'C': 5, 'H': 6, 'I': 7, 'M': 8, 'N': 9, 'T': 10, 'W': 11, 'Y': 12, 'a': 13, 'b': 14, 'c': 15, 'd': 16, 'e': 17, 'f': 18, 'g': 19, 'h': 20, 'i': 21, 'k': 22, 'l': 23, 'm': 24, 'n': 25, 'o': 26, 'p': 27, 'r': 28, 's': 29, 't': 30, 'u': 31, 'v': 32, 'w': 33, 'y': 34}


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
model = Sequential()
model.add(LSTM(80, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=150, verbose=2)

Epoch 1/150
27/27 - 2s - loss: 3.4666 - accuracy: 0.1151
Epoch 2/150
27/27 - 0s - loss: 3.0824 - accuracy: 0.1953
Epoch 3/150
27/27 - 0s - loss: 2.9932 - accuracy: 0.1953
Epoch 4/150
27/27 - 0s - loss: 2.9618 - accuracy: 0.1953
Epoch 5/150
27/27 - 0s - loss: 2.9436 - accuracy: 0.1953
Epoch 6/150
27/27 - 0s - loss: 2.9079 - accuracy: 0.1977
Epoch 7/150
27/27 - 0s - loss: 2.8482 - accuracy: 0.2267
Epoch 8/150
27/27 - 0s - loss: 2.7734 - accuracy: 0.2198
Epoch 9/150
27/27 - 0s - loss: 2.7019 - accuracy: 0.2419
Epoch 10/150
27/27 - 0s - loss: 2.6138 - accuracy: 0.2651
Epoch 11/150
27/27 - 0s - loss: 2.5405 - accuracy: 0.2826
Epoch 12/150
27/27 - 0s - loss: 2.4591 - accuracy: 0.3012
Epoch 13/150
27/27 - 0s - loss: 2.3632 - accuracy: 0.3407
Epoch 14/150
27/27 - 0s - loss: 2.2926 - accuracy: 0.3523
Epoch 15/150
27/27 - 0s - loss: 2.2052 - accuracy: 0.3791
Epoch 16/150
27/27 - 0s - loss: 2.1209 - accuracy: 0.4000
Epoch 17/150
27/27 - 0s - loss: 2.0462 - accuracy: 0.4174
Epoch 18/150
27/27 - 0s

In [ ]:
def sentence_generation_two(model, char_to_index, seq_length, seed_text, n):
# 모델, 인덱스 정보, 문장 길이, 초기 시퀀스, 반복 횟수
    init_text = seed_text # 문장 생성에 사용할 초기 시퀀스
    sentence = ''

    for _ in range(n): # n번 반복
        encoded = [char_to_index[char] for char in seed_text] # 현재 시퀀스에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=seq_length, padding='pre') # 데이터에 대한 패딩
        encoded = to_categorical(encoded, num_classes=len(char_to_index))
        resulttwo = model.predict(encoded, verbose=0) #predict_classes 없어져서 코드 바꿈
        result=np.argmax(resulttwo,axis=1)
        # 입력한 X(현재 시퀀스)에 대해서 y를 예측하고 y(예측한 글자)를 result에 저장.
        for char, index in char_to_index.items(): # 만약 예측한 글자와 인덱스와 동일한 글자가 있다면
            if index == result: # 해당 글자가 예측 글자이므로 break
                break
        seed_text=seed_text + char # 현재 시퀀스 + 예측 글자를 현재 시퀀스로 변경
        sentence=sentence + char # 예측 글자를 문장에 저장
        # for문이므로 이 작업을 다시 반복
        

    sentence = init_text + sentence
    return sentence

In [ ]:
print(sentence_generation_two(model, char_to_index, 10, 'It won\'t ', 50))

It won't be long, we'll meet again. Your memory is never pa


In [ ]:
#pdf 다운로드 링크: https://drive.google.com/file/d/1iPxzBRHbB1CY4597Rn4G75Pj6c7zDG3Q/view?usp=sharing